### ISSUE TITLE
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax

### ISSUE THREAD

**Issue by mwkcoding** [spatie/laravel-stats#12]
The method `getLatestSetPerPeriod` returns a MySQL error due to incorrect query:
```sql
select ROW_NUMBER() OVER (PARTITION BY date_format(created_at,'%Y-%m-%d') ORDER BY `id` DESC) AS rn, ...
```
What it should be:
```sql
select (ROW_NUMBER() OVER (PARTITION BY date_format(created_at,'%Y-%m-%d') ORDER BY `id` DESC)) AS rn, ...
```

The top version of the query throws errors even in a pure MySQL CLI which precludes that it's any issue in the project or PHP.

MySQL version: 8.0.26
Package version: 1.0.0
PHP version: 8.0.9
Laravel version: 8.60.0

**Comment by rappasoft** [comment]
I too am getting this error.
