### ISSUE TITLE
Support for php7

### ISSUE THREAD

**Issue by ikramooe** [spatie/laravel-stats#15]
Can you please add support from php 7

**Comment by riasvdv** [comment]
![image](https://user-images.githubusercontent.com/3626559/152117909-8d897927-4199-4e5a-8a28-4b519b4511a1.png)

PHP 7 support is ending, 7.4 only receives security updates, you might want to consider upgrading to PHP 8 instead. 

You're also free to fork this package and add PHP 7 support if you really need it!
