### ISSUE TITLE
Reading stat issue when using PostgreSQL

### ISSUE THREAD

**Issue by fun4life1990** [spatie/laravel-stats#20]
### My environment
* PHP 8.1 in Docker
* PostgreSQL 13.4 in Docker
* Laravel 9.0.1
* spatie/laravel-stats 2.0.1

When saving stats al works perfect. I have issue when reading stats in this way:
```
MyStats::query()
   ->start(Carbon::now())
   ->end(Carbon::now())
   ->groupByDay()
   ->get()
```

What I get as error:
`SQLSTATE[42883]: Undefined function: 7 ERROR:  function date_format(timestamp without time zone, unknown) does not exist\nLINE 1: ... 0 end)) as decrements, sum(value) as difference, date_forma...\n                                                             ^\nHINT:  No function matches the given name and argument types. You might need to add explicit type casts. (SQL: select sum(case when value > 0 then value else 0 end) as increments, abs(sum(case when value < 0 then value else 0 end)) as decrements, sum(value) as difference, date_format(created_at,'%Y-%m-%d') as period from \"stats_events\" where (\"name\" = users) and \"type\" = change and \"created_at\" >= 2022-04-12 09:09:00 and \"created_at\" < 2022-04-12 09:09:00 group by date_format(created_at,'%Y-%m-%d'))`

I think your method **getPeriodDateFormat** only supports mysql and sqlite, could you please add support for PostgreSQL?

Thanks!

**Comment by freekmurze** [comment]
We're not using Postgres, so we're not going to invest time in that.
