### ISSUE TITLE
Connection prefix not resolved in StatsQuery getStatsTableName

### ISSUE THREAD

**Issue by digitalkreativ** [spatie/laravel-stats#21]
I needed a simple stats tracking thing for a project and of course Spatie has a package for it. Thank you very much!

Unfortunately I came across an issue when the database connection uses a prefix, for example **test_** (`config/database.php`)

```
 'mysql' => [
    'driver' => 'mysql',
    'host' => env('DB_HOST', '127.0.0.1'),
    'port' => env('DB_PORT', '3306'),
    'database' => env('DB_DATABASE', 'forge'),
    'username' => env('DB_USERNAME', 'forge'),
    'password' => env('DB_PASSWORD', ''),
    'unix_socket' => env('DB_SOCKET', ''),
    'charset' => 'utf8mb4',
    'collation' => 'utf8mb4_unicode_ci',
    'prefix' => env('DB_PREFIX', ''),
    'prefix_indexes' => true,
    'strict' => true,
    'engine' => null,
    'options' => array_filter([
        PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
    ]),
],
```

the code below fails

```
SubscriptionStats::query()->start(Carbon::now()->subMinutes(5))->end(Carbon::now()->addMinutes(30))->get();
```

with the following message

```
 Illuminate\Database\QueryException 

  SQLSTATE[42S02]: Base table or view not found: 1051 Unknown table 'db_name.stats_events' (SQL: select ROW_NUMBER() OVER (PARTITION BY yearweek(created_at, 3) ORDER BY `id` DESC) AS rn, `stats_events`.*, yearweek(created_at, 3) as period from `test_stats_events` where (`name` = test) and `type` = set and `created_at` >= 2022-05-25 15:12:43 and `created_at` < 2022-05-25 15:47:43)
```

Thats the query being built at [#L252](https://github.com/spatie/laravel-stats/blob/main/src/StatsQuery.php#L252)

The culprit being the `$subject->getTable()` which does not add the connection prefix to the table name while using `selectRaw`.

A fix could be fetching the connection name and prefix like below ([#L284](https://github.com/spatie/laravel-stats/blob/main/src/StatsQuery.php#L284))

```
/** @var Model $subject */
$subject = $this->subject;
$prefix = '';
if (is_string($subject) && class_exists($subject)) {
    $subject = new $subject;
    $connectionName = $subject->getConnectionName() ?: config('database.default');
    $config = Config::get('database.connections.'.$connectionName);
    if( isset( $config['prefix'] ) && !empty( $config['prefix']) ){
        $prefix = $config['prefix'];
    }
}

return $prefix. $subject->getTable();
```

Most likely this would also need to happen for the `Relation` at [#L280](https://github.com/spatie/laravel-stats/blob/main/src/StatsQuery.php#L280)

Although that might warrant some extra thought as we don't want to duplicate the above code at multiple places.

I can probably make a pull request for this if needed. I'm just not really sure what kind of test(s) would be required for this to have "enough" coverage for this specific issue.

test_it_can_resolve_connection_prefix_of_table ?

I haven't checked the other spatie packages if there have been issues similar to this yet. That's probably for the upcoming long weekend.

**Comment by digitalkreativ** [comment]
I did some more research/digging. 

The code for $subject could be more simplified I think. ([#L284](https://github.com/spatie/laravel-stats/blob/main/src/StatsQuery.php#L284))

```
/** @var Model $subject */
$subject = $this->subject;
if (is_string($subject) && class_exists($subject)) {
    $subject = new $subject;
}

return $subject->getGrammar()->getTablePrefix() . $subject->getTable();
```

**Comment by christoph-kluge** [comment]
I contributed those lines. To me this looks good and the `selectRaw` explaination makes totally sense. I would recommend adding the prefix to #L281 as well. My contributation added the feature for HasMany-Relationships. In such a scenario it would fail as well.

And since you've been asking for the tests: In my opinion I would cover it once for the model-case and another test for `HasMany`-relationship case.
